In [2]:
import numpy as np

# ChatGPT was used to help confirm the diagonal dominance check

def is_diagonally_dominant(A):
    for i in range(len(A)):
        diag = abs(A[i][i])
        row_sum = 0

        for j in range(len(A)):
            if j != i:
                row_sum += abs(A[i][j])

        if diag < row_sum:
            return False

    return True


A = np.array([[4,1,2],
              [1,3,1],
              [0,1,5]])

print("Is the matrix diagonally dominant?", is_diagonally_dominant(A))
print(A)

B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Is the matrix diagonally dominant?", is_diagonally_dominant(B))
print(B)

Is the matrix diagonally dominant? True
[[4 1 2]
 [1 3 1]
 [0 1 5]]
Is the matrix diagonally dominant? False
[[1 2 3]
 [4 5 6]
 [7 8 9]]
